name: Maven CI/CD

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: build
      run: |
        cd backend/nitconf
        mvn -B package

    # Run tests
    - name: Run Tests
      run: |
        cd backend/nitconf
        mvn test